server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      directory: logs
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      pattern: "%{yyyy-MM-dd HH:mm:ss}t %s %r %{User-Agent}i %{Referer}i %a %b %D"

#swagger
springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger.html
    enabled: true
    operationsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true    #try it out 했을 때 request duration 을 추가로 찍어줌
#    groups-order: DESC
  api-docs:
      enabled: true
      path: /api-docs

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: oseek
    url: jdbc:mysql://43.201.10.241:3306/oseek?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    password: "xxxx"
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: 'update'

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://43.201.10.241:3306/oseek?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false
#    username: oseek
#    password: "oseek123456"
#  jpa:
#    properties:
#      hibernate:
#        format_sql: 'true'
#    show-sql: 'true'
#    hibernate:
#      ddl-auto: 'update'

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace